'use strict'

window._ = require 'lodash'
window.FaCompass = require 'react-icons/lib/fa/compass'
window.FaClose = require 'react-icons/lib/fa/close'
window.FaDownload = require 'react-icons/lib/fa/download'
window.FaFile = require 'react-icons/lib/fa/file'
window.FaFloppyO = require 'react-icons/lib/fa/floppy-o'
window.FaFolderOpen = require 'react-icons/lib/fa/folder-open'
window.FaLocationArrow = require 'react-icons/lib/fa/location-arrow'
# use it for single balise
window.FaUpload = require 'react-icons/lib/fa/upload'
window.Hoverboard = require 'hoverboard'
window.MdAvTimer = require 'react-icons/lib/md/av-timer'
window.React = require 'react'
window.ReactDOM = require 'react-dom'
